from setuptools import setup

setup(
    name='resonantgeodata',
    version='0.1',
    python_requires='>=3.8.0',
    install_requires=[
        'celery',
        'django>=3.1',
        'django-admin-display',
        'django-allauth',
        'django-cleanup',
        'django-configurations[database,email]',
        'django-cors-headers',
        'django-crispy-forms',
        'django-extensions',
        'django-girders',
        'django-filter',
        'django-model-utils',
        'django-s3-file-field>=0.0.11',
        'django-storages',
        'djangorestframework',
        'djproxy',
        'docker',
        'drf-yasg',
        'gputil',
        'psycopg2',
        'python-magic',
        'rich',
        'rules',
        'uritemplate',
        'whitenoise[brotli]',
        # Production-only
        'django-storages[boto3]',
        'flower',
        'gunicorn',
        # Development-only
        'django-debug-toolbar',
        'django-minio-storage',
        # GeoData
        'GDAL',
        'rasterio',
        'fiona',
        'shapely',
        'scipy',
    ],
    extras_require={'dev': ['ipython', 'tox']},
)
