# Generated by Django 3.0.3 on 2020-04-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algorithmjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmjob',
            name='algorithm_result',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='core.AlgorithmResult',
            ),
        ),
    ]
