# Generated by Django 3.0.3 on 2020-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='docker_image_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
