# Generated by Django 3.0.3 on 2020-04-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_algorithm_docker_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmjob',
            name='algorithm_result',
        ),
        migrations.RemoveField(
            model_name='algorithmresult',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='algorithmresult',
            name='dataset',
        ),
        migrations.AddField(
            model_name='algorithmresult',
            name='algorithm_job',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.AlgorithmJob',
            ),
        ),
        migrations.AddField(
            model_name='algorithmresult',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='result_logs'),
        ),
    ]
