# Generated by Django 3.0.3 on 2020-04-27 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20200424_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreresult',
            name='algorithmresult',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='groundtruth',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='scorealgorithm',
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='scores_logs'),
        ),
        migrations.AlterField(
            model_name='scorealgorithm',
            name='data',
            field=models.FileField(upload_to='score_algorithm'),
        ),
        migrations.CreateModel(
            name='ScoreJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('queued', 'Queued for processing'), ('running', 'Processing'), ('internal_failure', 'Internal failure'), ('failed', 'Failed'), ('success', 'Succeeded')], default='queued', max_length=20)),
                ('fail_reason', models.TextField(blank=True)),
                ('algorithm_results', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.AlgorithmResult')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('groundtruth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Groundtruth')),
                ('score_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ScoreAlgorithm')),
            ],
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='score_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ScoreJob'),
        ),
    ]
