# Generated by Django 3.0.3 on 2020-04-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200427_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorejob',
            old_name='algorithm_results',
            new_name='algorithm_result',
        ),
    ]
