# Generated by Django 3.0.3 on 2020-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200427_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorealgorithm',
            name='docker_image_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
