# Generated by Django 3.0.3 on 2020-05-05 20:14
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scorealgorithm_docker_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='data',
            field=models.FileField(
                upload_to='algorithm',
                validators=[core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='algorithmjob',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('internal_failure', 'Internal failure'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='queued',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='scorealgorithm',
            name='data',
            field=models.FileField(
                upload_to='score_algorithm',
                validators=[core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='scorejob',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('internal_failure', 'Internal failure'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='queued',
                max_length=20,
            ),
        ),
    ]
