# Generated by Django 3.0.6 on 2020-05-11 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200505_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='result_type',
            field=models.CharField(blank=True, choices=[('simple', 'Direct value'), ('roc', 'Receiver Operating Characteristic')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmjob',
            name='fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scorejob',
            name='fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
