# Generated by Django 3.0.6 on 2020-05-11 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200507_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(1.0),
                    django.core.validators.MinValueValidator(0.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='result_type',
            field=models.CharField(
                blank=True,
                choices=[('simple', 'Direct value'), ('roc', 'Receiver Operating Characteristic')],
                max_length=10,
                null=True,
            ),
        ),
    ]
