# Generated by Django 3.0.6 on 2020-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200511_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='docker_attrs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='docker_validation_failure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='docker_attrs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorealgorithm',
            name='docker_validation_failure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
