# Generated by Django 3.0.6 on 2020-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200505_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(blank=True, default=0.17653539111522776, null=True),
        ),
    ]
