# Generated by Django 3.0.6 on 2020-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200507_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmresult',
            name='data_mimetype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
