# Generated by Django 3.0.6 on 2020-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_algorithmresult_log_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='docker_attrs',
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='docker_validation_failure',
        ),
        migrations.RemoveField(
            model_name='scorealgorithm',
            name='docker_attrs',
        ),
        migrations.RemoveField(
            model_name='scorealgorithm',
            name='docker_validation_failure',
        ),
        migrations.AddField(
            model_name='algorithmresult',
            name='log_message',
            field=models.TextField(default='This only show the end of the log'),
        ),
        migrations.AddField(
            model_name='algorithmresult',
            name='log_preview',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='log_message',
            field=models.TextField(default='This only show the end of the log'),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='log_preview',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
