# Generated by Django 3.0.7 on 2020-06-26 13:59

from django.db import migrations
import s3_file_field.fields

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_postgis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000,
                upload_to='algorithm',
                validators=[core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='algorithmresult',
            name='data',
            field=s3_file_field.fields.S3FileField(max_length=2000, upload_to='results'),
        ),
        migrations.AlterField(
            model_name='algorithmresult',
            name='log',
            field=s3_file_field.fields.S3FileField(
                blank=True, max_length=2000, null=True, upload_to='results_logs'
            ),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=s3_file_field.fields.S3FileField(max_length=2000, upload_to='dataset'),
        ),
        migrations.AlterField(
            model_name='groundtruth',
            name='data',
            field=s3_file_field.fields.S3FileField(max_length=2000, upload_to='groundtruth'),
        ),
        migrations.AlterField(
            model_name='scorealgorithm',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000,
                upload_to='score_algorithm',
                validators=[core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='data',
            field=s3_file_field.fields.S3FileField(max_length=2000, upload_to='scores'),
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='log',
            field=s3_file_field.fields.S3FileField(
                blank=True, max_length=2000, null=True, upload_to='scores_logs'
            ),
        ),
    ]
