# Generated by Django 3.0.6 on 2020-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200506_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(blank=True, default=0.015102215321004753, null=True),
        ),
    ]
