# Generated by Django 3.0.6 on 2020-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200506_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreresult',
            name='data',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='log',
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
