# Generated by Django 3.0.6 on 2020-05-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200506_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreresult',
            name='overall_score',
            field=models.FloatField(default=0.043252286921018124),
        ),
    ]
