# Generated by Django 3.0.6 on 2020-05-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200506_2133'),
        ('core', '0012_auto_20200507_1615'),
    ]

    operations = [
    ]
