# Generated by Django 3.1.5 on 2021-01-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsampledimage',
            name='sample_type',
            field=models.CharField(
                choices=[
                    ('pixel box', 'Pixel bounding box'),
                    ('geographic box', 'Geographic bounding box'),
                    ('geojson', 'GeoJSON feature'),
                    ('annotation', 'Annotation entry'),
                ],
                default='pixel box',
                max_length=20,
            ),
        ),
    ]
