# Generated by Django 3.1.2 on 2020-11-17 21:15

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedimagefile',
            name='file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000,
                null=True,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
            ),
        ),
    ]
