# Generated by Django 3.1.2 on 2020-10-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandmetaentry',
            name='nodata_value',
            field=models.FloatField(null=True),
        ),
    ]
