# Generated by Django 3.1.5 on 2021-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checksumfile',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='checksumfile',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
    ]
