# Generated by Django 3.1.2 on 2020-11-03 18:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialentry',
            name='footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='spatialentry',
            name='outline',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
