# Generated by Django 3.1.5 on 2021-01-26 02:17

from django.db import migrations, models
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksumfile',
            name='file',
            field=s3_file_field.fields.S3FileField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checksumfile',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
