# Generated by Django 3.2a1 on 2021-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksumfile',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fmventry',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='geometryentry',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imageentry',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rasterentry',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
