# Generated by Django 3.1.1 on 2020-09-15 21:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields

import geodata.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMVFile',
            fields=[
                (
                    'modifiableentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='geodata.modifiableentry',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('compute_checksum', models.BooleanField(default=False)),
                ('validate_checksum', models.BooleanField(default=False)),
                ('last_validation', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('file', s3_file_field.fields.S3FileField(max_length=2000, upload_to='files/fmv/')),
            ],
            options={
                'abstract': False,
            },
            bases=('geodata.modifiableentry', geodata.models.mixins.TaskEventMixin),
        ),
        migrations.CreateModel(
            name='FMVEntry',
            fields=[
                (
                    'spatialentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to='geodata.spatialentry',
                    ),
                ),
                (
                    'modifiableentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='geodata.modifiableentry',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'klv_file',
                    s3_file_field.fields.S3FileField(
                        blank=True, max_length=2000, null=True, upload_to='files/fmv/'
                    ),
                ),
                (
                    'web_video_file',
                    s3_file_field.fields.S3FileField(
                        blank=True, max_length=2000, null=True, upload_to='files/fmv/web/'
                    ),
                ),
                (
                    'ground_frame',
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    'flight_path',
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    'fmv_file',
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.fmvfile'
                    ),
                ),
            ],
            bases=('geodata.modifiableentry', 'geodata.spatialentry'),
        ),
    ]
