# Generated by Django 3.1.5 on 2021-01-14 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20210111_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedimagefile',
            name='converted_file',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='geodata.arbitraryfile',
            ),
        ),
        migrations.AlterField(
            model_name='subsampledimage',
            name='data',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='geodata.arbitraryfile',
            ),
        ),
    ]
