# Generated by Django 3.1.5 on 2021-01-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20210111_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedimagefile',
            name='converted_file',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.arbitraryfile'
            ),
        ),
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='image_set',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.imageset'
            ),
        ),
        migrations.AlterField(
            model_name='subsampledimage',
            name='data',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.arbitraryfile'
            ),
        ),
    ]
