# Generated by Django 3.1.6 on 2021-02-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20210211_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksumfile',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checksumfiles',
                related_query_name='checksumfiles',
                to='geodata.collection',
            ),
        ),
    ]
