# Generated by Django 3.1 on 2020-10-05 19:03

from django.db import migrations
import s3_file_field.fields

import rgd.geodata.models.geometry.base


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20200929_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitraryfile',
            name='file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='fmventry',
            name='klv_file',
            field=s3_file_field.fields.S3FileField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
            ),
        ),
        migrations.AlterField(
            model_name='fmventry',
            name='web_video_file',
            field=s3_file_field.fields.S3FileField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
            ),
        ),
        migrations.AlterField(
            model_name='fmvfile',
            name='file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='geometryarchive',
            name='file',
            field=s3_file_field.fields.S3FileField(
                help_text='This must be an archive (`.zip` or `.tar`) of a single shape (`.shp`, `.dbf`, `.shx`, etc.).',
                max_length=2000,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                validators=[rgd.geodata.models.geometry.base.validate_archive],
            ),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
    ]
