# Generated by Django 3.1.4 on 2020-12-18 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_subsampledimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsampledimage',
            name='source_image',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='geodata.imageentry'
            ),
        ),
    ]
