# Generated by Django 3.2a1 on 2021-03-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20210301_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageentry',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='imageentry',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='imageentry',
            name='status',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
