# Generated by Django 3.1.5 on 2021-01-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitraryfile',
            name='collection',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='arbitraryfiles',
                related_query_name='arbitraryfiles',
                to='geodata.collection',
            ),
        ),
        migrations.AddField(
            model_name='fmvfile',
            name='collection',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='fmvfiles',
                related_query_name='fmvfiles',
                to='geodata.collection',
            ),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='collection',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='geometryarchives',
                related_query_name='geometryarchives',
                to='geodata.collection',
            ),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='collection',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='imagefiles',
                related_query_name='imagefiles',
                to='geodata.collection',
            ),
        ),
    ]
