# Generated by Django 3.1.2 on 2020-10-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20201005_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                (
                    'modifiableentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='geodata.modifiableentry',
                    ),
                ),
                ('base_thumbnail', models.ImageField(blank=True, upload_to='thumbnails')),
                (
                    'image_entry',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='geodata.imageentry',
                    ),
                ),
            ],
            bases=('geodata.modifiableentry',),
        ),
    ]
