# Generated by Django 3.1.2 on 2020-10-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitraryfile',
            name='compute_checksum',
        ),
        migrations.RemoveField(
            model_name='convertedimagefile',
            name='compute_checksum',
        ),
        migrations.RemoveField(
            model_name='fmvfile',
            name='compute_checksum',
        ),
        migrations.RemoveField(
            model_name='geometryarchive',
            name='compute_checksum',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='compute_checksum',
        ),
    ]
