# Generated by Django 3.2a1 on 2021-03-12 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_auto_20210309_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastermetaentry',
            name='cloud_cover',
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
