# Generated by Django 3.1.2 on 2020-10-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_auto_20201015_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedimagefile',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='fmvfile',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='kwcocoarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='rasterentry',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                ],
                default='created',
                max_length=20,
            ),
        ),
    ]
