# Generated by Django 3.2 on 2021-04-23 04:13

from django.db import migrations
import s3_file_field.fields

import rgd.utility


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_rasterentry_ancillary_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksumfile',
            name='file',
            field=s3_file_field.fields.S3FileField(
                blank=True, null=True, upload_to=rgd.utility.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='fmvfile',
            name='klv_file',
            field=s3_file_field.fields.S3FileField(
                null=True, upload_to=rgd.utility.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='fmvfile',
            name='web_video_file',
            field=s3_file_field.fields.S3FileField(
                null=True, upload_to=rgd.utility.uuid_prefix_filename
            ),
        ),
    ]
