# Generated by Django 3.2 on 2021-05-05 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0010_auto_20210423_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterentry',
            name='ancillary_files',
            field=models.ManyToManyField(blank=True, to='geodata.ChecksumFile'),
        ),
        migrations.AlterField(
            model_name='rastermetaentry',
            name='cloud_cover',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
