# Generated by Django 3.2.2 on 2021-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_auto_20210505_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedEmail',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
