# Generated by Django 3.2.2 on 2021-05-11 05:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_auto_20210505_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialentry',
            name='footprint',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.CreateModel(
            name='SpatialAsset',
            fields=[
                (
                    'spatialentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='geodata.spatialentry',
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('files', models.ManyToManyField(to='geodata.ChecksumFile')),
            ],
            bases=('geodata.spatialentry',),
        ),
    ]
