# Generated by Django 3.2.2 on 2021-05-11 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geodata', '0012_whitelistedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='users',
        ),
    ]
