# Generated by Django 3.2.3 on 2021-05-27 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0017_imagesetspatial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialentry',
            name='outline',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
