# Generated by Django 3.2.4 on 2021-06-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0018_alter_spatialentry_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionpermission',
            name='role',
            field=models.SmallIntegerField(
                choices=[(1, 'Reader'), (2, 'Owner')],
                db_index=True,
                default=1,
                help_text='A "reader" can view assets in this collection. An "owner" can additionally add/remove other users, set their permissions, delete the collection, and add/remove other files.',
            ),
        ),
    ]
