# Generated by Django 3.2.4 on 2021-06-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatialasset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spatialasset',
            name='name',
        ),
        migrations.AddField(
            model_name='checksumfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
