# Generated by Django 3.2.4 on 2021-07-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialasset',
            options={},
        ),
        migrations.RenameField(
            model_name='spatialentry',
            old_name='footprint',
            new_name='feature',
        ),
    ]
