# Generated by Django 3.2.8 on 2021-11-03 19:00

from django.db import migrations, models
import django.db.models.deletion


def move_collection_to_file_set(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ChecksumFile = apps.get_model('rgd', 'ChecksumFile')
    FileSet = apps.get_model('rgd', 'FileSet')
    for file in ChecksumFile.objects.all():
        if file.collection:
            if not file.file_set:
                file.file_set = FileSet.objects.create()
            file.file_set.collection = file.collection
            file.file_set.save()
            file.save(
                update_fields=[
                    'file_set',
                ]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0005_auto_20211105_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='collection',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='filesets',
                related_query_name='filesets',
                to='rgd.collection',
            ),
        ),
        migrations.RunPython(move_collection_to_file_set),
        migrations.RemoveField(
            model_name='checksumfile',
            name='collection',
        ),
    ]
