# Generated by Django 3.2.10 on 2021-12-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0005_auto_20211105_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checksumfile',
            name='url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
