# Generated by Django 3.2.8 on 2021-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0005_auto_20211102_1828'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checksumfile',
            constraint=models.UniqueConstraint(fields=('file_set', 'name'), name='unique_name'),
        ),
    ]
