# Generated by Django 3.2.8 on 2021-11-09 03:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import rgd.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0005_auto_20211105_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Credentials',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=127)),
                ('aws_access_key_id', models.CharField(max_length=128)),
                ('aws_secret_access_key', models.CharField(max_length=255)),
                ('region', models.CharField(default='us-east-1', max_length=63)),
                (
                    'collection',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='rgd.collection'
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, rgd.models.mixins.PermissionPathMixin),
        ),
    ]
