# Generated by Django 3.2.8 on 2021-11-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0006_checksumfile_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
