# Generated by Django 3.2.10 on 2022-01-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_3d', '0004_auto_20211116_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh3dspatial',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
