# Generated by Django 3.1 on 2020-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageentry', name='metadata', field=models.JSONField(null=True),
        ),
    ]
