# Generated by Django 3.1rc1 on 2020-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='imageentry', name='image_set',),
        migrations.AddField(
            model_name='imageset',
            name='images',
            field=models.ManyToManyField(to='geodata.ImageEntry'),
        ),
    ]
