# Generated by Django 3.0.7 on 2020-06-26 13:59

from django.db import migrations
import s3_file_field.fields

import geodata.models.geometry.base


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedrasterfile',
            name='converted_file',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='geometryarchive',
            name='archive_file',
            field=s3_file_field.fields.S3FileField(
                help_text='This must be an archive (`.zip` or `.tar`) of a single shape (`.shp`, `.dbf`, `.shx`, etc.).',
                max_length=2000,
                upload_to='files/geometry_files',
                validators=[geodata.models.geometry.base.validate_archive],
            ),
        ),
        migrations.AlterField(
            model_name='rasterfile',
            name='raster_file',
            field=s3_file_field.fields.S3FileField(max_length=2000, upload_to='files/rasters'),
        ),
    ]
