# Generated by Django 3.0.7 on 2020-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20200626_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometryarchive',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
