# Generated by Django 3.1 on 2020-09-10 15:33

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_fmventry_fmvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmventry',
            name='klv_file',
            field=s3_file_field.fields.S3FileField(
                blank=True, max_length=2000, null=True, upload_to='files/fmv/'
            ),
        ),
    ]
