# Generated by Django 3.1 on 2020-09-10 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_fmventry_klv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmventry',
            name='flight_path',
            field=django.contrib.gis.db.models.fields.MultiPointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name='fmventry',
            name='ground_frame',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
