# Generated by Django 3.1rc1 on 2020-08-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20200813_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwcocodataset',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
