# Generated by Django 3.0.7 on 2020-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20200710_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedrasterfile',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
    ]
