# Generated by Django 3.0.7 on 2020-07-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20200709_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterfile',
            name='compute_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rasterfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
