# Generated by Django 3.1 on 2020-09-15 15:47

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20200910_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmventry',
            name='web_video_file',
            field=s3_file_field.fields.S3FileField(blank=True, max_length=2000, null=True, upload_to='files/fmv/web/'),
        ),
    ]
