# Generated by Django 3.0.8 on 2020-07-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20200713_1309'),
    ]

    operations = [
        migrations.RemoveField(model_name='geometryentry', name='acquisition_date',),
        migrations.RemoveField(model_name='geometryentry', name='description',),
        migrations.RemoveField(model_name='geometryentry', name='footprint',),
        migrations.RemoveField(model_name='geometryentry', name='modifiableentry_ptr',),
        migrations.RemoveField(model_name='geometryentry', name='name',),
        migrations.RemoveField(model_name='rasterentry', name='acquisition_date',),
        migrations.RemoveField(model_name='rasterentry', name='description',),
        migrations.RemoveField(model_name='rasterentry', name='footprint',),
        migrations.RemoveField(model_name='rasterentry', name='modifiableentry_ptr',),
        migrations.RemoveField(model_name='rasterentry', name='name',),
        migrations.AlterField(
            model_name='geometryentry',
            name='spatialentry_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='geodata.SpatialEntry',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rasterentry',
            name='spatialentry_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='geodata.SpatialEntry',
            ),
            preserve_default=False,
        ),
    ]
