# Generated by Django 3.1 on 2020-08-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20200814_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KWCOCODataset',
            new_name='KWCOCOArchive',
        ),
    ]
