# Generated by Django 3.0.7 on 2020-07-15 17:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_auto_20200713_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convertedrasterfile', old_name='converted_file', new_name='file',
        ),
        migrations.RenameField(
            model_name='geometryarchive', old_name='archive_file', new_name='file',
        ),
        migrations.RenameField(model_name='rasterfile', old_name='raster_file', new_name='file',),
        migrations.RemoveField(model_name='geometryarchive', name='geometry_entry',),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='compute_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='convertedrasterfile',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='compute_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryarchive',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geometryentry',
            name='geometry_archive',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.GeometryArchive'
            ),
        ),
        migrations.AddField(
            model_name='rasterentry',
            name='outline',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='compute_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='last_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rasterfile',
            name='validate_checksum',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                (
                    'modifiableentry_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='geodata.ModifiableEntry',
                    ),
                ),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('bounding_box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    'feature',
                    django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
                ),
                ('annotator', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                (
                    'raster',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='geodata.RasterEntry'
                    ),
                ),
            ],
            bases=('geodata.modifiableentry',),
        ),
    ]
