# Generated by Django 3.1 on 2020-08-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_auto_20200817_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwcocoarchive',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.imageset'),
        ),
    ]
