# Generated by Django 3.0.7 on 2020-07-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_auto_20200714_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geometryarchive',
            name='geometry_entry',
        ),
        migrations.AddField(
            model_name='geometryentry',
            name='geometry_archive',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.GeometryArchive'),
        ),
    ]
