# Generated by Django 3.1 on 2020-08-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_kwcocoarchive_image_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='geodata.imageset'),
        ),
    ]
