# Generated by Django 3.1 on 2020-08-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_auto_20200817_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='segmentation',
        ),
        migrations.AddField(
            model_name='segmentation',
            name='annotation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='geodata.annotation'),
            preserve_default=False,
        ),
    ]
