FROM joncrall/urban3d_v2:latest

CMD bash -c '\
mkdir /tmp/dataset >&2 && \
tar -zxv -C /tmp/dataset >/dev/null && \
ls -l /tmp/dataset >&2 && \
source /root/conda_bashrc.sh >&2 && \
python -m clab.live.final test --train_data_path=/data/training --test_data_path=/tmp/dataset --output_file=results >&2 && \
cat results.txt \
'

