# An image for extracting the KLV metadata from FMV datasets usign Kwiver
# This accepts a movie file on stdin and produces the KLV metadata on stdout
# This is pushed to https://hub.docker.com/repository/docker/banesullivan/kwiver/tags
#  under the tage `dump-klv`
#
# Usage:
#   cat video.mpg | docker run -i banesullivan/kwiver:dump-klv > video.klv
FROM kitware/kwiver:latest

# NOTE: vodeo file extension does not matter.
CMD bash -c '\
  cat > fmv.video && \
  /kwiver/build/bin/kwiver dump-klv fmv.video \
'
