# Generated by Django 3.1 on 2020-10-05 19:03

from django.db import migrations
import s3_file_field.fields

import rgd.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                validators=[rgd.core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='algorithmresult',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='algorithmresult',
            name='log',
            field=s3_file_field.fields.S3FileField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
            ),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='groundtruth',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='scorealgorithm',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
                validators=[rgd.core.validators.MimetypeValidator(['application/x-tar'])],
            ),
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='data',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
        migrations.AlterField(
            model_name='scoreresult',
            name='log',
            field=s3_file_field.fields.S3FileField(
                blank=True,
                max_length=2000,
                null=True,
                upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename,
            ),
        ),
    ]
