# Generated by Django 3.2.4 on 2021-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmeta',
            name='dtype',
        ),
    ]
