# Generated by Django 3.2.4 on 2021-06-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
