# Generated by Django 3.2.5 on 2021-07-13 10:17

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmeta',
            name='band_range',
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(
                help_text='The spectral range of the band (in micrometers).', null=True
            ),
        ),
    ]
