# Generated by Django 3.2.5 on 2021-08-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0002_bandmeta_band_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmeta',
            name='dtype',
        ),
    ]
