# Generated by Django 3.2.5 on 2021-08-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0003_resampledimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertedimage',
            name='add_to_sets',
            field=models.BooleanField(
                default=True,
                help_text='Add this image to the ImageSets that the source image belongs to.',
            ),
        ),
        migrations.AddField(
            model_name='regionimage',
            name='add_to_sets',
            field=models.BooleanField(
                default=True,
                help_text='Add this image to the ImageSets that the source image belongs to.',
            ),
        ),
        migrations.AddField(
            model_name='resampledimage',
            name='add_to_sets',
            field=models.BooleanField(
                default=True,
                help_text='Add this image to the ImageSets that the source image belongs to.',
            ),
        ),
    ]
