# Generated by Django 3.2.6 on 2021-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0004_auto_20210820_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
