# Generated by Django 3.2.5 on 2021-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0004_auto_20210810_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='secondary',
            field=models.ManyToManyField(related_name='_rgd_imagery_imageset_secondary_+', to='rgd_imagery.Image'),
        ),
    ]
