# Generated by Django 3.2.5 on 2021-08-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0005_imageset_secondary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='secondary',
            field=models.ManyToManyField(blank=True, null=True, related_name='_rgd_imagery_imageset_secondary_+', to='rgd_imagery.Image'),
        ),
    ]
