# Generated by Django 3.2.7 on 2021-09-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0005_raster_extra_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemeta',
            name='number_of_bands',
        ),
    ]
