# Generated by Django 3.2.7 on 2021-09-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0006_remove_imagemeta_number_of_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                    ('skipped', 'Skipped'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='kwcocoarchive',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                    ('skipped', 'Skipped'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                    ('skipped', 'Skipped'),
                ],
                default='created',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='raster',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created but not queued'),
                    ('queued', 'Queued for processing'),
                    ('running', 'Processing'),
                    ('failed', 'Failed'),
                    ('success', 'Succeeded'),
                    ('skipped', 'Skipped'),
                ],
                default='created',
                max_length=20,
            ),
        ),
    ]
