# Generated by Django 3.2.10 on 2021-12-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rgd_imagery', '0007_auto_20210927_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KWCOCOArchive',
        ),
    ]
