# Generated by Django 4.0.3 on 2022-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgd', '0009_alter_checksumfile_collection_and_more'),
        ('rgd_imagery', '0009_alter_processedimage_processed_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='ancillary_files',
            field=models.ManyToManyField(blank=True, related_name='+', to='rgd.checksumfile'),
        ),
        migrations.AlterField(
            model_name='raster',
            name='ancillary_files',
            field=models.ManyToManyField(blank=True, related_name='+', to='rgd.checksumfile'),
        ),
    ]
