name: Publish Dev Wheels to GitHub Pages

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main

jobs:
  # Upload wheels to GH Pages package index
  build-wheels:
    name: Build Wheels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rgd-module: ['django-rgd', 'django-rgd/client', 'django-rgd-3d', 'django-rgd-fmv', 'django-rgd-geometry', 'django-rgd-imagery', 'django-rgd-imagery/client']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: pip install setuptools wheel
      - name: Build Weel
        working-directory: ${{ matrix.rgd-module }}
        run: python setup.py sdist bdist_wheel
      - name: Set Cache Name
        run:
          CACHE_NAME=$(echo ${{ matrix.rgd-module }} | sed 's/\//\-/g')
          echo "CACHE_NAME=$CACHE_NAME" >> $GITHUB_ENV
      - name: Cache Wheel
        uses: actions/upload-artifact@v2
        with:
          name: pkg-$CACHE_NAME
          path: ${{ matrix.rgd-module }}/dist/
  publish-wheels:
    name: Publish Wheels
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
      - uses: actions/download-artifact@v2
        with:
          # Downloads all artifacts
          path: packages/
      - name: Make index
        uses: banesullivan/create-pip-index-action@main
        with:
          package_directory:  packages/
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  packages/
