name: RGD Package Release
on:
  push:
    tags: "*"
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rgd-module: ['django-rgd', 'django-rgd/client', 'django-rgd-3d', 'django-rgd-fmv', 'django-rgd-geometry', 'django-rgd-imagery', 'django-rgd-imagery/client', 'django-composed-configuration-rgd']
        include:
          - rgd-module: django-rgd
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD
          - rgd-module: django-rgd/client
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_CLIENT
          - rgd-module: django-rgd-3d
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_3D
          - rgd-module: django-rgd-fmv
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_FMV
          - rgd-module: django-rgd-geometry
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_GEOMETRY
          - rgd-module: django-rgd-imagery
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_IMAGERY
          - rgd-module: django-rgd-imagery/client
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_RGD_IMAGERY_CLIENT
          - rgd-module: django-composed-configuration-rgd
            TWINE_PASSWORD_VAR: PYPI_API_TOKEN_COMPOSED_CONFIGURATION_RGD

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build and Publish to PyPI
        working-directory: ${{ matrix.rgd-module }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets[matrix.TWINE_PASSWORD_VAR] }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --skip-existing dist/*
