name: RGD Client Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: "**"
jobs:
  rgd-client:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        image: bitnami/minio:latest
        env:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Test rgd-client
        run: |
          tox -e test-rgd-client
        env:
          MINIO_STORAGE_ENDPOINT: minio:9000
