name: RGD Client Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: "**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Install rgdc
        working-directory: ./rgd-client
        run: pip install -e .
      - name: Test (not implemented)
        working-directory: ./rgd-client
        run: python -c "from rgdc import Rgdc; print('Import went okay!')"
